var momentumfilter =['all',['match',['get', 'oevk_name'],[],true,false]]
var lmpfilter =['all',['match',['get', 'oevk_name'],[],true,false]]
var dkfilter =['all',['match',['get', 'oevk_name'],[],true,false]]
var mszpfilter =['all',['match',['get', 'oevk_name'],[],true,false]]
var parbeszedfilter =['all',['match',['get', 'oevk_name'],[],true,false]]
var jobbikfilter =['all',['match',['get', 'oevk_name'],[],true,false]]
var uvnpfilter =['all',['match',['get', 'oevk_name'],[],true,false]]
$('.dkpart').on('click', function() {{
map.setFilter('valterk2',dkfilter);
map.setFilter('valterk3',dkfilter);
$('.dkpart').addClass("selected2");
$('.jobbikpart').addClass("unselected");
$('.jobbikpart span').css("background-color","rgba(0,0,0,0)");
$('.lmppart').addClass("unselected");
$('.lmppart span').css("background-color","rgba(0,0,0,0)");
$('.momentumpart').addClass("unselected");
$('.momentumpart span').css("background-color","rgba(0,0,0,0)");
$('.mszppart').addClass("unselected");
$('.mszppart span').css("background-color","rgba(0,0,0,0)");
$('.parbeszedpart').addClass("unselected");
$('.parbeszedpart span').css("background-color","rgba(0,0,0,0)");
$('.uvnppart').addClass("unselected");
$('.uvnppart span').css("background-color","rgba(0,0,0,0)");
$('.dkpart span').css("background-color","rgba(0,113,255,1)");
$('.dkpart').removeClass("unselected");
$('.jobbikpart').removeClass("selected2");
$('.lmppart').removeClass("selected2");
$('.momentumpart').removeClass("selected2");
$('.mszppart').removeClass("selected2");
$('.partbeszedpart').removeClass("selected2");
$('.uvnppart').removeClass("selected2");
$('#yesfilter').css("display", "none");
$('#nofilter').css("display", "block");
map.setPaintProperty('valterk2', 'fill-color', ['match',['feature-state', 'nyertespart'],"DK","rgba(0,113,255,1)","Jobbik","rgba(0,135,114,1)","LMP","rgba(75,210,0,1)","Momentum","rgba(151,97,211,1)","MSZP","rgba(249,0,0,1)","Párbeszéd","rgba(0,187,63,1)","MMM","rgba(12,0,106,1)","Új Világ Néppárt","rgba(219,47,137,1)","#ccc",]);
map.setLayoutProperty('szekhelyekujuj-0izoff', 'visibility', 'visible');;map.setFilter('szekhelyekujuj-0izoff',dkfilter);
map.setLayoutProperty('valterk3', 'visibility', 'visible');map.setLayoutProperty('szekhelyek-dkosmv', 'visibility', 'none');map.setFilter('szekhelyek-dkosmv',null);map.setLayoutProperty('szavazohelyekuj-4mfy4k', 'visibility', 'none');
$('#prop2').val("");}});
$('.jobbikpart').on('click', function() {{
map.setFilter('valterk2',jobbikfilter);
map.setFilter('valterk3',jobbikfilter);
$('.jobbikpart').addClass("selected2");
$('.dkpart').addClass("unselected");
$('.dkpart span').css("background-color","rgba(0,0,0,0)");
$('.lmppart').addClass("unselected");
$('.lmppart span').css("background-color","rgba(0,0,0,0)");
$('.momentumpart').addClass("unselected");
$('.momentumpart span').css("background-color","rgba(0,0,0,0)");
$('.mszppart').addClass("unselected");
$('.mszppart span').css("background-color","rgba(0,0,0,0)");
$('.parbeszedpart').addClass("unselected");
$('.parbeszedpart span').css("background-color","rgba(0,0,0,0)");
$('.uvnppart').addClass("unselected");
$('.uvnppart span').css("background-color","rgba(0,0,0,0)");
$('.jobbikpart span').css("background-color","rgba(0,135,114,1)");
$('.jobbikpart').removeClass("unselected");
$('.dkpart').removeClass("selected2");
$('.lmppart').removeClass("selected2");
$('.momentumpart').removeClass("selected2");
$('.mszppart').removeClass("selected2");
$('.partbeszedpart').removeClass("selected2");
$('.uvnppart').removeClass("selected2");
$('#yesfilter').css("display", "none");
$('#nofilter').css("display", "block");
map.setPaintProperty('valterk2', 'fill-color', ['match',['feature-state', 'nyertespart'],"DK","rgba(0,113,255,1)","Jobbik","rgba(0,135,114,1)","LMP","rgba(75,210,0,1)","Momentum","rgba(151,97,211,1)","MSZP","rgba(249,0,0,1)","Párbeszéd","rgba(0,187,63,1)","MMM","rgba(12,0,106,1)","Új Világ Néppárt","rgba(219,47,137,1)","#ccc",]);
map.setLayoutProperty('szekhelyekujuj-0izoff', 'visibility', 'visible');;map.setFilter('szekhelyekujuj-0izoff',jobbikfilter);
map.setLayoutProperty('valterk3', 'visibility', 'visible');map.setLayoutProperty('szekhelyek-dkosmv', 'visibility', 'none');map.setFilter('szekhelyek-dkosmv',null);map.setLayoutProperty('szavazohelyekuj-4mfy4k', 'visibility', 'none');
$('#prop2').val("");}});
$('.lmppart').on('click', function() {{
map.setFilter('valterk2',lmpfilter);
map.setFilter('valterk3',lmpfilter);
$('.lmppart').addClass("selected2");
$('.jobbikpart').addClass("unselected");
$('.jobbikpart span').css("background-color","rgba(0,0,0,0)");
$('.dkpart').addClass("unselected");
$('.dkpart span').css("background-color","rgba(0,0,0,0)");
$('.momentumpart').addClass("unselected");
$('.momentumpart span').css("background-color","rgba(0,0,0,0)");
$('.mszppart').addClass("unselected");
$('.mszppart span').css("background-color","rgba(0,0,0,0)");
$('.parbeszedpart').addClass("unselected");
$('.parbeszedpart span').css("background-color","rgba(0,0,0,0)");
$('.uvnppart').addClass("unselected");
$('.uvnppart span').css("background-color","rgba(0,0,0,0)");
$('.lmppart span').css("background-color","rgba(75,210,0,1)");
$('.lmppart').removeClass("unselected");
$('.jobbikpart').removeClass("selected2");
$('.dkpart').removeClass("selected2");
$('.momentumpart').removeClass("selected2");
$('.mszppart').removeClass("selected2");
$('.partbeszedpart').removeClass("selected2");
$('.uvnppart').removeClass("selected2");
$('#yesfilter').css("display", "none");
$('#nofilter').css("display", "block");
map.setPaintProperty('valterk2', 'fill-color', ['match',['feature-state', 'nyertespart'],"DK","rgba(0,113,255,1)","Jobbik","rgba(0,135,114,1)","LMP","rgba(75,210,0,1)","Momentum","rgba(151,97,211,1)","MSZP","rgba(249,0,0,1)","Párbeszéd","rgba(0,187,63,1)","MMM","rgba(12,0,106,1)","Új Világ Néppárt","rgba(219,47,137,1)","#ccc",]);
map.setLayoutProperty('szekhelyekujuj-0izoff', 'visibility', 'visible');;map.setFilter('szekhelyekujuj-0izoff',lmpfilter);
map.setLayoutProperty('valterk3', 'visibility', 'visible');map.setLayoutProperty('szekhelyek-dkosmv', 'visibility', 'none');map.setFilter('szekhelyek-dkosmv',null);map.setLayoutProperty('szavazohelyekuj-4mfy4k', 'visibility', 'none');
$('#prop2').val("");}});
$('.momentumpart').on('click', function() {{
map.setFilter('valterk2',momentumfilter);
map.setFilter('valterk3',momentumfilter);
$('.momentumpart').addClass("selected2");
$('.jobbikpart').addClass("unselected");
$('.jobbikpart span').css("background-color","rgba(0,0,0,0)");
$('.lmppart').addClass("unselected");
$('.lmppart span').css("background-color","rgba(0,0,0,0)");
$('.dkpart').addClass("unselected");
$('.dkpart span').css("background-color","rgba(0,0,0,0)");
$('.mszppart').addClass("unselected");
$('.mszppart span').css("background-color","rgba(0,0,0,0)");
$('.parbeszedpart').addClass("unselected");
$('.parbeszedpart span').css("background-color","rgba(0,0,0,0)");
$('.uvnppart').addClass("unselected");
$('.uvnppart span').css("background-color","rgba(0,0,0,0)");
$('.momentumpart span').css("background-color","rgba(151,97,211,1)");
$('.momentumpart').removeClass("unselected");
$('.jobbikpart').removeClass("selected2");
$('.lmppart').removeClass("selected2");
$('.dkpart').removeClass("selected2");
$('.mszppart').removeClass("selected2");
$('.partbeszedpart').removeClass("selected2");
$('.uvnppart').removeClass("selected2");
$('#yesfilter').css("display", "none");
$('#nofilter').css("display", "block");
map.setPaintProperty('valterk2', 'fill-color', ['match',['feature-state', 'nyertespart'],"DK","rgba(0,113,255,1)","Jobbik","rgba(0,135,114,1)","LMP","rgba(75,210,0,1)","Momentum","rgba(151,97,211,1)","MSZP","rgba(249,0,0,1)","Párbeszéd","rgba(0,187,63,1)","MMM","rgba(12,0,106,1)","Új Világ Néppárt","rgba(219,47,137,1)","#ccc",]);
map.setLayoutProperty('szekhelyekujuj-0izoff', 'visibility', 'visible');;map.setFilter('szekhelyekujuj-0izoff',momentumfilter);
map.setLayoutProperty('valterk3', 'visibility', 'visible');map.setLayoutProperty('szekhelyek-dkosmv', 'visibility', 'none');map.setFilter('szekhelyek-dkosmv',null);map.setLayoutProperty('szavazohelyekuj-4mfy4k', 'visibility', 'none');
$('#prop2').val("");}});
$('.mszppart').on('click', function() {{
map.setFilter('valterk2',mszpfilter);
map.setFilter('valterk3',mszpfilter);
$('.mszppart').addClass("selected2");
$('.jobbikpart').addClass("unselected");
$('.jobbikpart span').css("background-color","rgba(0,0,0,0)");
$('.lmppart').addClass("unselected");
$('.lmppart span').css("background-color","rgba(0,0,0,0)");
$('.momentumpart').addClass("unselected");
$('.momentumpart span').css("background-color","rgba(0,0,0,0)");
$('.dkpart').addClass("unselected");
$('.dkpart span').css("background-color","rgba(0,0,0,0)");
$('.parbeszedpart').addClass("unselected");
$('.parbeszedpart span').css("background-color","rgba(0,0,0,0)");
$('.uvnppart').addClass("unselected");
$('.uvnppart span').css("background-color","rgba(0,0,0,0)");
$('.mszppart span').css("background-color","rgba(249,0,0,1)");
$('.mszppart').removeClass("unselected");
$('.jobbikpart').removeClass("selected2");
$('.lmppart').removeClass("selected2");
$('.momentumpart').removeClass("selected2");
$('.dkpart').removeClass("selected2");
$('.partbeszedpart').removeClass("selected2");
$('.uvnppart').removeClass("selected2");
$('#yesfilter').css("display", "none");
$('#nofilter').css("display", "block");
map.setPaintProperty('valterk2', 'fill-color', ['match',['feature-state', 'nyertespart'],"DK","rgba(0,113,255,1)","Jobbik","rgba(0,135,114,1)","LMP","rgba(75,210,0,1)","Momentum","rgba(151,97,211,1)","MSZP","rgba(249,0,0,1)","Párbeszéd","rgba(0,187,63,1)","MMM","rgba(12,0,106,1)","Új Világ Néppárt","rgba(219,47,137,1)","#ccc",]);
map.setLayoutProperty('szekhelyekujuj-0izoff', 'visibility', 'visible');;map.setFilter('szekhelyekujuj-0izoff',mszpfilter);
map.setLayoutProperty('valterk3', 'visibility', 'visible');map.setLayoutProperty('szekhelyek-dkosmv', 'visibility', 'none');map.setFilter('szekhelyek-dkosmv',null);map.setLayoutProperty('szavazohelyekuj-4mfy4k', 'visibility', 'none');
$('#prop2').val("");}});
$('.parbeszedpart').on('click', function() {{
map.setFilter('valterk2',parbeszedfilter);
map.setFilter('valterk3',parbeszedfilter);
$('.parbeszedpart').addClass("selected2");
$('.jobbikpart').addClass("unselected");
$('.jobbikpart span').css("background-color","rgba(0,0,0,0)");
$('.lmppart').addClass("unselected");
$('.lmppart span').css("background-color","rgba(0,0,0,0)");
$('.momentumpart').addClass("unselected");
$('.momentumpart span').css("background-color","rgba(0,0,0,0)");
$('.mszppart').addClass("unselected");
$('.mszppart span').css("background-color","rgba(0,0,0,0)");
$('.dkpart').addClass("unselected");
$('.dkpart span').css("background-color","rgba(0,0,0,0)");
$('.uvnppart').addClass("unselected");
$('.uvnppart span').css("background-color","rgba(0,0,0,0)");
$('.parbeszedpart span').css("background-color","rgba(0,187,63,1)");
$('.parbeszedpart').removeClass("unselected");
$('.jobbikpart').removeClass("selected2");
$('.lmppart').removeClass("selected2");
$('.momentumpart').removeClass("selected2");
$('.mszppart').removeClass("selected2");
$('.dkpart').removeClass("selected2");
$('.uvnppart').removeClass("selected2");
$('#yesfilter').css("display", "none");
$('#nofilter').css("display", "block");
map.setPaintProperty('valterk2', 'fill-color', ['match',['feature-state', 'nyertespart'],"DK","rgba(0,113,255,1)","Jobbik","rgba(0,135,114,1)","LMP","rgba(75,210,0,1)","Momentum","rgba(151,97,211,1)","MSZP","rgba(249,0,0,1)","Párbeszéd","rgba(0,187,63,1)","MMM","rgba(12,0,106,1)","Új Világ Néppárt","rgba(219,47,137,1)","#ccc",]);
map.setLayoutProperty('szekhelyekujuj-0izoff', 'visibility', 'visible');;map.setFilter('szekhelyekujuj-0izoff',parbeszedfilter);
map.setLayoutProperty('valterk3', 'visibility', 'visible');map.setLayoutProperty('szekhelyek-dkosmv', 'visibility', 'none');map.setFilter('szekhelyek-dkosmv',null);map.setLayoutProperty('szavazohelyekuj-4mfy4k', 'visibility', 'none');
$('#prop2').val("");}});
$('.uvnppart').on('click', function() {{
map.setFilter('valterk2',uvnpfilter);
map.setFilter('valterk3',uvnpfilter);
$('.uvnppart').addClass("selected2");
$('.jobbikpart').addClass("unselected");
$('.jobbikpart span').css("background-color","rgba(0,0,0,0)");
$('.lmppart').addClass("unselected");
$('.lmppart span').css("background-color","rgba(0,0,0,0)");
$('.momentumpart').addClass("unselected");
$('.momentumpart span').css("background-color","rgba(0,0,0,0)");
$('.mszppart').addClass("unselected");
$('.mszppart span').css("background-color","rgba(0,0,0,0)");
$('.parbeszedpart').addClass("unselected");
$('.parbeszedpart span').css("background-color","rgba(0,0,0,0)");
$('.dkpart').addClass("unselected");
$('.dkpart span').css("background-color","rgba(0,0,0,0)");
$('.uvnppart span').css("background-color","rgba(219,47,137,1)");
$('.uvnppart').removeClass("unselected");
$('.jobbikpart').removeClass("selected2");
$('.lmppart').removeClass("selected2");
$('.momentumpart').removeClass("selected2");
$('.mszppart').removeClass("selected2");
$('.partbeszedpart').removeClass("selected2");
$('.dkpart').removeClass("selected2");
$('#yesfilter').css("display", "none");
$('#nofilter').css("display", "block");
map.setPaintProperty('valterk2', 'fill-color', ['match',['feature-state', 'nyertespart'],"DK","rgba(0,113,255,1)","Jobbik","rgba(0,135,114,1)","LMP","rgba(75,210,0,1)","Momentum","rgba(151,97,211,1)","MSZP","rgba(249,0,0,1)","Párbeszéd","rgba(0,187,63,1)","MMM","rgba(12,0,106,1)","Új Világ Néppárt","rgba(219,47,137,1)","#ccc",]);
map.setLayoutProperty('szekhelyekujuj-0izoff', 'visibility', 'visible');;map.setFilter('szekhelyekujuj-0izoff',uvnpfilter);
map.setLayoutProperty('valterk3', 'visibility', 'visible');map.setLayoutProperty('szekhelyek-dkosmv', 'visibility', 'none');map.setFilter('szekhelyek-dkosmv',null);map.setLayoutProperty('szavazohelyekuj-4mfy4k', 'visibility', 'none');
$('#prop2').val("");}});
$('#nofilter').on('click', function() {{
$('#yesfilter').css("display", "block");
$('#nofilter').css("display", "none");
map.setFilter('valterk2',null);
map.setFilter('valterk3',null);
$('.dkpart').removeClass("selected2");
$('.jobbikpart').removeClass("unselected");
$('.lmppart').removeClass("unselected");
$('.momentumpart').removeClass("unselected");
$('.mszppart').removeClass("unselected");
$('.parbeszedpart').removeClass("unselected");
$('.uvnppart').removeClass("unselected");
$('.dkpart span').css("background-color","rgba(0,113,255,1)");
$('.jobbikpart span').css("background-color","rgba(0,135,114,1)");
$('.lmppart span').css("background-color","rgba(75,210,0,1)");
$('.momentumpart span').css("background-color","rgba(151,97,211,1)");
$('.mszppart span').css("background-color","rgba(249,0,0,1)");
$('.parbeszedpart span').css("background-color","rgba(0,187,63,1)");
$('.uvnppart span').css("background-color","rgba(219,47,137,1)");
$('.dkpart').removeClass("unselected");
$('.jobbikpart').removeClass("selected2");
$('.lmppart').removeClass("selected2");
$('.momentumpart').removeClass("selected2");
$('.mszppart').removeClass("selected2");
$('.parbeszedpart').removeClass("selected2");
$('.uvnppart').removeClass("selected2");
$('.dkpart').removeClass("unselected");
$('.jobbikpart').removeClass("selected2");
$('.lmppart').removeClass("selected2");
$('.momentumpart').removeClass("selected2");
$('.mszppart').removeClass("selected2");
$('.parbeszedpart').removeClass("selected2");
$('.uvnppart').removeClass("selected2");
$('.dkpart').removeClass("selected2");
$('.jobbikpart').removeClass("unselected");
$('.lmppart').removeClass("unselected");
$('.momentumpart').removeClass("unselected");
$('.mszppart').removeClass("unselected");
$('.parbeszedpart').removeClass("unselected");
$('.uvnppart').removeClass("unselected");
map.setLayoutProperty('szekhelyekujuj-0izoff', 'visibility', 'none');map.setFilter('szekhelyekujuj-0izoff',null);
map.setPaintProperty('valterk2', 'fill-color', ['match',['feature-state', 'nyertespart'],"DK","rgba(0,113,255,1)","Jobbik","rgba(0,135,114,1)","LMP","rgba(75,210,0,1)","Momentum","rgba(151,97,211,1)","MSZP","rgba(249,0,0,1)","Párbeszéd","rgba(0,187,63,1)","MMM","rgba(12,0,106,1)","Új Világ Néppárt","rgba(219,47,137,1)","#ccc",]);
map.setFilter('szavazohelyekuj-4mfy4k',null);map.setLayoutProperty('valterk3', 'visibility', 'visible');map.setLayoutProperty('szekhelyek-dkosmv', 'visibility', 'none');map.setFilter('szekhelyek-dkosmv',null);map.setLayoutProperty('szavazohelyekuj-4mfy4k', 'visibility', 'none');
$('#prop2').val("");
$('#prop4').val("");}});
